<?php
SYSTEM\autoload::registerFolder(dirname(__FILE__),'');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/default_page','');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/default_register','');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/default_comment','');

SYSTEM\autoload::registerFolder(dirname(__FILE__).'/user_main_votelist','');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/user_main_analysis','');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/user_main_options','');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/user_main_poll','');


//SYSTEM\autoload::registerFolder(dirname(__FILE__).'/user_list_ended','');
//SYSTEM\autoload::registerFolder(dirname(__FILE__).'/user_main','');
//SYSTEM\autoload::registerFolder(dirname(__FILE__).'/user_main_uVote','');
//SYSTEM\autoload::registerFolder(dirname(__FILE__).'/user_list','');